# Generated by Django 3.1.7 on 2021-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='Insert details here...'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='Insert details here...'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animalcategory',
            name='animal',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Hamster', 'Hamster')], max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
